-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 21, 2017 at 12:35 PM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 7.1.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `database`
--

-- --------------------------------------------------------

--
-- Table structure for table `courses`
--

DROP TABLE IF EXISTS `courses`;
CREATE TABLE IF NOT EXISTS `courses` (
  `course_id` int(11) NOT NULL,
  `course_name` varchar(100) NOT NULL,
  `course_short_name` varchar(6) NOT NULL,
  `institute_id` varchar(6) NOT NULL,
  `semester` int(11) NOT NULL,
  `syllabus` varchar(10000) NOT NULL,
  `reference` varchar(1000) NOT NULL,
  `branch` varchar(10) NOT NULL,
  `lecture` int(11) NOT NULL,
  `tutorial` int(11) NOT NULL,
  `lab` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `courses`
--

INSERT INTO `courses` (`course_id`, `course_name`, `course_short_name`, `institute_id`, `semester`, `syllabus`, `reference`, `branch`, `lecture`, `tutorial`, `lab`) VALUES
(0, 'MATHEMATICS I ', 'MTH101', '1', 1, 'Real numbers, Sequences; Series; Power series, Limit, \r\nContinuity; Differentiability, Mean value theorems \r\nand applications; Linear Approxima\r\ntion, Newton and Picard L-T-P-D-[C] \r\n3-1-0-1-[4] L-T-\r\nP-D-[C] 2-0-0-0-\r\n[0] L-T-P-D-[C] 3-1-0-1-[4\r\n] 313 method, Taylor¿s theorem (one va\r\nriable), Approxima\r\ntion by polynomials, \r\nCritical points, convex\r\nity, Curve tracing, Riemann Integral, fundame\r\nntal theorems of integral calculus, \r\nImproper integrals, Trapezoidal and Simpson¿s rule; e\r\nrror bounds, Space coordinates, lines and planes, Polar \r\ncoordinates, Graphs of polar equa\r\ntions; Cylinders, Quadric surfaces, \r\nVolume, Area, length; Continuity, \r\nDifferentiability of vector functions\r\n, arc length; Curvature, \r\ntorsion, Serret-Frenet formulas, Functions of two \r\nor more variables, partial derivatives Statem\r\nent only, of Taylor¿s theorem and criteria for \r\nmaxima/Minima/saddle points, Double, triple integrals,\r\n Jacobians; Surf\r\naces, integrals, Vector Calculus, \r\nGreen, Gauss, Stokes Theorems.', 'Lecture Notes', 'all', 0, 0, 0),
(2, 'physics-II', 'phy103', '1', 1, 'Course Contents:\r\nVector calculus; electrostatics; Gau\r\nss law and applications, electrostatic \r\npotentialand curl of E; work and \r\nenergy in electrostatics, Laplaces equation and \r\n(first)LTPD[C]1020[0]CoreLTPD[\r\nC]0003[2]CoreLTPD[C]3110[4]Core\r\nLTPD[C]3110[4]Core384uniqueness \r\ntheorem, method of images, multipoles (introducti\r\non), force andtorque on dipoles; polarization, bound \r\ncharges, electric displacementand boundary conditions\r\n, linear dielectrics, force on dielectrics; motion \r\nofcharges in electric & magnetic fiel\r\nds; magnetostatics: current density,curl and divergence of B, Ampres law \r\nand applications, magnetization, boundcurrents a\r\nnd bound pole densities, magnetic field H, magnetic \r\nsusceptibility,ferro, para and diamagnetism, boundary \r\nconditions on B and H, Faradayslaw, energy in \r\nmagnetic field, displacement current, Maxwells equations\r\n inmedia, Poyntings theorem, e.m. waves: wave \r\nequation, plane waves, polarizationand types of pol\r\narization, energy and momentum of plane e.m. \r\nwaves.propagation through linear medi\r\na and conductors. reflection and tr\r\nansmissionat normal incidence from \r\ndielectric and metal interfaces. magn\r\netism as arelativistic phenolmenon, rela\r\ntivistic transformations of E and \r\nB fields (simpleillustrations only), diffraction, quantum \r\nmechanics, photons, uncertaintyprinciple, electron \r\ndiffraction experiments, de Broglie hypothesis, Bornin\r\nterpretation, Schrdinger equa\r\ntion and application to 1d \r\nbox problem. ', 'Electrodynamics by Griffiths', 'all', 3, 1, 0),
(3, 'physics-I', 'phy102', '1', 1, 'Transformation of Scalars and Vectors under Rotation, Fo\r\nrm Invariance of Newtons Second Law, Forces in \r\nNature; Solving Newtons Equations of Motion in Pola\r\nr Coordinates for problems including Constraint and \r\nFriction, extension to Cylindrical an\r\nd Spherical Coordinates; Potential \r\nEnergy Function, Conservative and \r\nNonConservative Forces; Central Forces, Energy E\r\nquation and Diagrams, Elliptical, Parabolic, and \r\nHyperbolic Orbits, Harmonic Oscillat\r\nor with Damping, Forced Oscillations and Resonance, inclusion of \r\nNonlinear Force and Chaotic Motion, PhaseSpace Descripti\r\non; NonInertial Frames of Reference, Centrifugal \r\nand Coriolis Forces, Weather Systems, Foucault \r\nPendulum; Angular Momentum and Torque, Rigid Body \r\nDynamics, Moment of Inertia Tensor, Principal Axes\r\n, TorqueFree Precession, Gyro\r\nscopes, Eulers Equations; \r\nSpecial Relativity, Lorentz Transformation, Length \r\nContraction, Time Dila\r\ntion, Velocity Addition, \r\nRelativistic Dynamics, EnergyMass Relation ', 'Kleppner', 'all', 3, 1, 0),
(4, 'mathematics-II', 'mth102', '1', 2, 'Matrices: matrix operations (Additio\r\nn, Scalar Multiplication, Multiplica\r\ntion,Transpose, Adjoint and their \r\nproperties; Special types of matrices (Null, Iden\r\ntity,Diagonal, Triangular, Symm\r\netric, SkewSymmetric, \r\nHermitian, SkewHermitian,Orthogonal, Unitary, Normal\r\n), Solution of the matrix Equation Ax b; \r\nRowreducedEchelon form, Determinants and their pr\r\noperties, Vector Space Rn(R);Subspaces; Linear \r\nDependence/Independence; Basis; Sta\r\nndard Basis of Rn;Dimension; Coordi\r\nnates with respect to a basis; \r\nComplementary Subspaces;Standard Inner \r\nproduct; Norm; GramSchmidt Orthogonalization \r\nProcess;Generalization to the vector\r\n space Cn(C), Linear Transformati\r\non from Rn toRm (motivation, X* \r\nAX); Image of a basis identifies th\r\ne linear transformation;Range Space and Rank; Null Space and Nullity; \r\nMatrix Representation of a lineartransformation; Struct\r\nure of the solutions of th\r\ne matrix equation Ax b; \r\nLinearOperators on Rn and their representation as s\r\nquare matrices; Similar Matricesand linear operators; \r\nInvertible linear operators; Inverse of a nonsingularma\r\ntrix; Cramers method to solve the matrix equation Ax \r\nb; Eigenvalues andeigenvector\r\ns of a linear operator; Charac\r\nteristic Equation; Bounds on \r\neigenvalues;Diagonalizability\r\n of a linear operator; \r\nProperties of eigenvalues and eigenvectorsof Hermitian, \r\nskewHermitian, Unitary, and Normal matrices (i\r\nncluding symmetric,skewsymmetric, and orthogonal \r\nmatrices), Implication of diagonala\r\nizability ofthe matrix A + AT in\r\n the real quadratic form XTAX; ', 'Lecture Notes', 'all', 3, 1, 0),
(5, 'chemistry laboratory', 'chm101', '1', 1, 'Chemical analysis with relevanc\r\ne to everyday lifeI. Determination \r\nof amount of Ca2+ in milk by \r\ncomplexometric titration2. Estimati\r\non of iodine in common iodized \r\nsalt by iodometry3. Estimation of \r\nphosphoric acid in cola drinks by \r\nmolybdenum bluemethod4. Analysis of\r\n kidney stone model chemical \r\ncompounds by permanganometric titratton5. Extracti\r\non of DNA from green pe\r\nas or onions and its \r\nidentification6. Extraction of caffeine,\r\n an alkaloid from tea leaves7. How many pigments are there in the \r\ngreen portion of spinach? A paper \r\nchromatographyexperiment to separa\r\nte the various pigments including \r\nchlorophyllSynthesis of Chemical CompoundsI. Prep\r\naration and characteriza\r\ntion of aspirin, a common \r\nmedicine2. DielsAlder reaction a vers\r\natile organic reaction to form CC \r\nbonds: a reaction betweenanthracene \r\nand maleic anhydride3. Preparation and characte\r\nrization of an inorgani\r\nc coordination complex \r\ncompound:[Ni[NH3]6f+ 2cr\r\n4. Organometallic compounds: bridge\r\ns between inorganic and organic \r\nCHEMISTRY \r\nLABORATORY \r\nPage \r\n108\r\n of \r\n474\r\ncompounds. AcetylationofF errocene5. \r\nAn environmentrelated synthesi\r\ns: Preparation of potash alum \r\nfromscrap aluminumPhotochemistry: Light as a reagen\r\nt in chemistryI. Photochemical reduction of ferric \r\noxalate and its use in blueprintingExperiments on Phys\r\nical Chemistry Conceptsl. Partition of solutes in \r\nmixture of solvents: Acetic acid inwater/nbutan\r\nol2. Kinetics of reactions: An example using the \r\niodidehydrogen peroxide clock reac\r\ntion3. Determining the pi of amino acids by using potentiometry4. Weak \r\nand strong acids and bases: conductometry ', 'A. J. Elias:\" A Collection oflntere\r\nsting General Chemistry Experiment\r\ns\". UniversitiesPress, Hyderabad, 2009 ', 'all', 0, 0, 3),
(6, 'general chemistry', 'chm102', '1', 2, 'Atomic Structure (4 Lectures). Ch\r\nemical Bonding (5 Lectures). Molecular Spcctmscopy (5 Lectures). \r\nCoordination complexes of transition metal ions (3 \r\nLectures). Organometallic Chemistry (3 Lectures). \r\nMolecular Structure of organic Compounds (3 Lectures\r\n). Organic Reactions of Industrial Relevance (4 \r\nLectures). Chemistry of New Materials: For example,\r\n Fullerenes, nanotubes and graphene (1 Lecture) ', '1. Atkins & Julio de Paula: Physic\r\nal Chemist1y, 8th Edition, Freeman & \r\nCo.2. Atkins & Shriver: Inorganic \r\nChemistry, 4th Edition (2008).3. Clayden, Greaves,\r\n Warren &Wothers: Organic Chemistry, Oxtbrd \r\nUniveisity Press. ', 'all', 2, 1, 0),
(7, 'physics laboratory', 'phy101', '1', 1, 'Introduction to error analysis and gr\r\naphdrawing; spring oscillation apparatu\r\ns;trajectory of a projectile on an \r\ninclined plane; moment of inerti\r\na of a bicyclewheel; bar pendulum; \r\ntorsional pendulum; coupled pendulum; \r\nstudy of collisionson an air track; gyroscope; \r\ncurrent balance; measurement of capacitance \r\nusinggalvanometer; charging of\r\n a plate capacitor; elec\r\ntromagnetic induction; pris\r\nmspectrometer; Fraunhofer \r\nPage \r\n442\r\n of \r\n474\r\ndiffraction using HeNe laser; magne\r\ntic fieldin Helmholtz coil; res\r\nonance in electrical circuits', 'Lab Manual', 'all', 0, 0, 3),
(8, 'fundamental of computing', 'esc101', '1', 1, 'Stored program concept (with simple computer\r\n simulator), machine language and instruction \r\nformats,assembly language for the simple computer. In\r\nteger representation, finite\r\n representation of real \r\nnumbers,overflow, underflow, errors due to finite repr\r\nesentations. Expressions, valu\r\nes and variables, types, \r\nlvalue,rvalue, unary, binary, tern\r\nary operations. Conditionals, ifthen, \r\nifthenelse, nested conditionals, \r\nswitchcase.Loops, for, while, repeat, loopinvariants,\r\n precondition, postcondition. Functions and return \r\nvalues,arguments, passbyvalue, effect of passing \r\npointers (like passbyreferen\r\nce). Recursion. Arrays, \r\nenums,searching, sorting. Pointers, lists, dynamic da\r\nta structures, stack, queu\r\ne, graphs, trees related \r\nalgorithms,memory and its management. Elementary complexity motivation, concrete complexity, big O \r\nnotation.Linux tools, introduction to shell progra\r\nmming. Elementary numerical problem solving will \r\naddressedlargely through some labs\r\n e.g. root finding, solutions of syst\r\nems of linear equations, integration, \r\nsolution ofODEs. ', '1. Brian W Kernighan and Dennis M Ritchi\r\ne, The C Programming Language,2nd Ed. ANSI C \r\nversion,Pearson, 2006. ', 'all', 3, 1, 3),
(9, 'introduction to biology', 'lif101', '1', 1, 'Part I Principles of Cellular LifeE\r\nffects of waters polarity\r\n: importance of cohesion of water molecules for \r\nlife; moderation of Earths temperature; Suitability of water as a solvent for life.Carbon and the molecular \r\ndiversity of life.Polymer principles\r\n: most macromolecules of life are pol\r\nymers; variety from a small set of \r\nmonomers.Carbohydrates stru\r\ncture and functionProteins structur\r\ne and functionLipids structure and \r\nfunctionNucleic acids structure and \r\nfunctionIntroduction to metabolism: \r\npathways; energy transformation in \r\norganisms follow the laws of therm\r\nodynamics; life at the expense of free\r\n energy; enzymes as biocatalysts; \r\nregulation of metabolismB. Cell: Struct\r\nural and functional unit of life (5\r\n lectures)Structure: how we study \r\ncells; birds eye view of cell structure; subcellular \r\nstructures; organelles; cytoskeleton; cell surface and \r\njunctionsMembrane structure and func\r\ntion; traffic across membranesCellular respiration; photosynthesis; cell \r\ncommunication; cell cyclePart II Principles of \r\nInheritance: Information processing in living \r\nsystemsIntroduction to heredity: \r\ninheritance of chromosomes; co\r\nmparison of asexual and sexual \r\nreproduction; meiosis and sexual life \r\ncycles; origins of ge\r\nnetic variationMendels discoveries; extending \r\nMendelian genetics; Mendelian inheri\r\ntance in humanChromosomal basis \r\nof inheritance: Relating Mendels \r\nprinciples to chromosomes; Sex \r\nchromosomes and sexlinked inherita\r\nnce; errors and exceptions in \r\nchromosomal inheritanceDNA as the genetic materi\r\nal; DNA replication and re\r\npairGene to protein: \r\nconnection between genes and proteins\r\n; synthesis and processing of RNA; \r\nsynthesis of proteinOrganization \r\nand control of prokaryotic genomesOr\r\nganization and control of eukaryot\r\nic genomes: chromatin structure; \r\ncontrol of gene expressionDNA \r\ntechnology and genomics: DNA cloning;\r\n DNA analysis and genomics; \r\npractical applications of DNA technologyGenetic basis of\r\n development: single cell \r\nto multicellula\r\nr organism; ', '', 'all', 2, 0, 0),
(10, 'engineering graphics', 'ta101', '1', 1, 'Introduction to sketching; Principal views, principles\r\n ofdimensioning Introduction \r\nto computeraidedgraphics \r\nMissing view, sectional view and assembly drawi\r\nngs Overview of pictorial representation, and \r\nisometricdrawing in detail Perspectiv\r\ne drawing Lines, planes, auxiliary \r\nview Relationship between lines and \r\nplanes intersection oflines and pl\r\nanes Intersections of solids and development of lateral surfaces ', '', 'all', 2, 0, 3),
(11, 'MATHEMATICS FOR \r\nCOMPUTER SCIENCE -I ', 'cs201a', '1', 3, '1. Mathematical proofs, proofs by induction, by contra\r\ndiction, proving the contrapositive.2. Basic counting \r\ntechniques, pigeonhole principle, re\r\ncurrence relations, generating functi\r\nons, principle of inclusionand \r\nexclusion, Mobius inversion.3. Graphs\r\n, trees definitions. Connectivity, paths, cycles, Eulerian walks, \r\nHamiltonian cycles, cliques, colourings,graph matc\r\nhing, planarity.4. Discrete probability. Sample space, \r\nevents, probability basic laws, discrete random variab\r\nle, expectation, linearityof \r\nexpectation, independence, \r\nconditioning, Bayes theorem, Bernoulli, binomial and \r\ngeometric distributions,moments and deviations, \r\nMarkov, Tchebyshev \'s inequalities, Chernoff bo\r\nunds.5. Application of pr\r\nobabilistic methods in combinatorics and graph theory. ', '1. Peter Cameron, Combinatorics: Topics, Techniques,\r\n Algorithms, Cambridge University Press, 1995.2. JH \r\nvan Lint, RM Wilson, A Course in Combinatorics,\r\n 2nd Ed., Cambridge University Press, 2001.3. David \r\nStirzaker, Elementary Probability, 2nd Ed., Cambridge \r\nUniversity Press, 2003.4. Noga Alan, Joel Spencer, \r\nThe Probabilistic Method, 3rd Ed., Wiley Interscience,\r\n 2008.5. R Graham, D Knuth, 0 Patashnik, Concrete \r\nMathematics: A Foundation for Computer\r\n Science, 2nd Ed.,AddisonWesley, 1994. ', 'cs', 3, 0, 0),
(12, 'MATHEMATICS FOR \r\nCOMPUTER SCIENCE -II ', 'cs202', '1', 3, '1. Propositional logic syntax and semantics.2. Ta\r\nutologies, axiom system \r\nand deduction.3. Proof of \r\nsoundness and completeness.4. First order logic syntax a\r\nnd semantics.5. Structures, models, satisfaction and \r\nvalidity.6. Axiomatization, soundness and comple\r\nteness.7. Optional: some advanced topics. ', '1. HD Ebbinghaus, J Flum, W Thomas\r\n, Mathematical Logic, 2nd Ed., Springer Verlag, 1994.2. HB Enderton, \r\nA Mathematical Introduction to Logic, 2nd Ed., Academ\r\nic Press, 2001.3. RM Smullyan, First Order Logic, \r\nDover Press, 1995. ', 'cs', 3, 0, 0),
(12, 'MATHEMATICS FOR \r\nCOMPUTER SCIENCE -III ', 'cs203', '1', 3, '1. Group theory: definition of groups, cosets and \r\nLagrange\'s theorem, subgroups, normal subgroups, \r\nquotientgroups, group action and Burnside\'s lemma.2. Rings\r\n, Fields, integral domains basic definitions and \r\nproperties. Field extensions, Chines\r\ne remaindering overintegers and polyn\r\nomial rings. (op\r\ntional: Introduction \r\nto finite fields.) ', '1. IN Herstein, Abstract Algebra,\r\n 3rd Ed., Wiley, 1996.2. DS Dummit, RM \r\nFoote, Abstract Algebra, John \r\nWiley, 2004. ', 'cs', 3, 0, 0),
(14, 'INTRODUCTION TO \r\nELECTRONICS ', 'esc201', '1', 3, 'Circuit analysis techniques (nodal, mesh, superposition, \r\nThevenins, andNortons theorems); Transient analysis \r\nof capacitive and inductive circuits; \r\nSinusoidal steadystateanalys\r\nis of circuits containing resistors, capacitors, \r\nand inductors; Transfer functions andfrequency re\r\nsponse; Semiconductors; Di\r\nodes and diode circuits; \r\nMOSFETs and amplifiers; ICfabricati\r\non; Operational amplifier circuits \r\nand waveform generators; Number \r\nsystem, logic gates,logic minimization, combinational \r\ncircuits; Field programmabl\r\ne gate arrays (FPGAs); \r\nFlipflops,sequential circuits, \r\ncounters, shift registers; data converters (DAC, ADC). ', '', 'all', 3, 1, 3),
(15, 'MANUFACTURING \r\nPROCESSES I ', 'ta201', '1', 3, 'Introduction to manufacturing:Evoluti\r\non of manufacturing, Engineering mate\r\nrials classification, Evolution of \r\nmanufacturing and its classi\r\nfications. Engineering Materi\r\nals: Structure of material\r\ns, Types of materials, \r\nProperties of materials, Microstructu\r\nreproperty interrelationshi\r\np. Casting/ Solidificati\r\non: Classifications of \r\ncasting processes, Patterns, Core making, Gating system\r\n, Solidificationof pure meta\r\nls and alloys, shrinkage, \r\ngas solubility, Riser design, Investme\r\nnt casting, Casting defects. Joini\r\nng processes: Fusion welding: Arc \r\n(MMAW, SAW, SMAW), Gas welding and resistance we\r\nlding, Fusion zone, Heat affected zone (HAZ), \r\nBrazing and Soldering, Solid state weld\r\ning processes, Thermit welding. De\r\nformation processes: Engineering \r\nstressstrain curve, Effect of temperature on the \r\nworkability, Extrusion (dir\r\nect and indirect)Rolling \r\nclassification, roll camber, defects, Fo\r\nrging (open and closeddie) Wire dr\r\nawing, Defects, Sheetmetal forming. \r\nPowder metallurgy: Introduction, Powder production, Co\r\nmpaction, and Sintering, Engineering stressstrain \r\ncurve. Plastic injection molding: \r\nFlow forming of plastic components.\r\n Heat Treatment: Special techniques \r\n(Nonconventional techniques). ', '', 'all', 1, 0, 3),
(16, 'MANUFACTURING \r\nPROCESSES II ', 'ta202', '1', 3, 'Engineering materials; Microstructu\r\nreprocessing relationship; Solidific\r\nationprocesses: molding and casting; \r\nJoining processes: welding, brazing, \r\nand soldering; Deformationprocesse\r\ns: hot and cold working, bulk and \r\nsheet forming; Powder metallurgica\r\nl processing:powder produ\r\nction, sintering; FeC phase diagram and heat \r\ntreatment; Surface modificationtech\r\nniques: carburization, CVD, P\r\nVD.Specialized Infrastructure \r\nrequirement:Rolling Mill, Pressure Die Casting Unit ', '', 'all', 1, 0, 3),
(17, 'COMMUNICATION SKILLS: COMPOSITION ', 'com200', '1', 3, '', '', 'all', 1, 0, 2),
(18, 'COMPUTER \r\nORGANIZATION ', 'cs220', '1', 4, '{a) Digital Design using HDLs. Simple\r\n circuit designs: For e.g. Counter, \r\nMultiplexer, Arithmetic circuits \r\netc.Design of a Simple Processor: Includes regist\r\ner file, ALU, data paths.{b) FPGA Programming \r\nProgramming on Xilinx Spartan 3E (or equivalent) \r\nFPGA.Handling of Inputs: \r\nthrough slide switches, \r\nthrough push buttons.Handling of Outputs: 7segment\r\n display, LED display, LCD display.The designs \r\ndeveloped in Part! can be used to program the \r\nFPGA.5(c) Assembly Language Programming Programming \r\nin assembly language. The assignments should cover th\r\nefollowing concepts:Registe\r\nrs; different type of \r\ninstructions (load, store, arithme\r\ntic, logic, branch); operand addressi\r\nng modes;memory addressing modes; \r\nconditions (codes/flags and \r\nconditional branches) stack manipulat\r\nion; procedurecalls; procedure call \r\nconventions (load/store of; argumen\r\nts on stack, activation records); ', '1. Computer Organization and Design: The Hardwa\r\nre/Software Interface, David A Patterson, John L. \r\nHennessy,4th Edition, Morgan Kaufmann, 20092. Comput\r\ner Architecture and Organization by William \r\nStallings, PHI Pvt. Ltd., Eastern Economy Edition, Si\r\nxthEdition, 20033. Structured \r\nComputer Organization \r\nby Andrew S Tanenbaum, PHI/Pearson, 4th Edition4. Co\r\nmputer Organization by V \r\nCarl Hamacher, Zvonks \r\nVranesic, SafeaZaky, McGraw Hill, Vth Edition5. \r\nComputer System Architecture by M Morris Mano, Prentice Hall of India, 20016. Comp\r\nuter Architecture and Or\r\nganization by John P Hayes, 3rd Ed. McGraw \r\nHill, 2002.7. Assembly Language, Online notes, http:/ /linuxassembly.orgj.8. Books related to HDL (Verilog, \r\nVHDL, BSV) programming. ', 'cs', 3, 0, 3),
(19, 'COMPUTING \r\nLABORATORY-I ', 'cs251', '1', 4, '1. Basic operating system commands. Students are expe\r\ncted to know the basic shell (e.g., bash) commands \r\nand should be able to understand \r\nthe options and functioning of a co\r\nmmand by reading the man and info \r\npages.2. Editors. Again, students are e\r\nxpected to be familiar with at l\r\neast one of the two editors vim and \r\nemacs. How ever, they should be able to utilize the \r\nmultiple features of the editors (such as automatic \r\nindentation, ontextsensitive\r\n colouring, letypesensitive autowrap, \r\netc.) and not use them simply as a \r\ntypewriter.3. Version control. Students will need to co\r\nmpletely know how at least one of the version control \r\nsystems (e.g., cvs, svn, git, dares) work. They_should be\r\n able to check in, check \r\nout, resolve errors and put \r\ntags on a snapshot. On all subsequent assignments, they\r\n must use a form of version .control.4. Scripting and \r\nautomation. Of the various types of shells (bash, csh, \r\ntcsh, ksh), the preferred \r\nchoice is bash, although \r\nstudents should be familiar with the different command synt\r\nax in other shells as well. Also, they will need to \r\nknow the various functions (e.g., seq, for) that a shell pr\r\novides. The choice of the scripting language(per! or \r\npython) is open to students.5. Document preparation. St\r\nudents will learn using latex for preparing documents. \r\nThey should also know how to format properly the equa\r\ntions, gures, tables, theore\r\nms, etc. using different \r\npackages and options. For bibliography management, they \r\nshould use bibtex, and must use it within the latex \r\ndocuments. For drawing gures and graphs, they can choos\r\ne to learn some or all of the different softwares \r\nused popularly (they includegnuplot, xfi\r\ng, etc.). 6. Hardware. Students will\r\n work handson to learn how to \r\ninstall hard drives, RAM, etc., and in general, \r\nassemble a computer from its different parts. ', '1. Manuals.2. Online help that is \r\navailable for different tools. ', 'cs', 1, 0, 3),
(20, 'DATA STRUCTURE & \r\nALGORITHM ', 'eso207', '1', 4, 'Order Analysis: Objectives of time analysis of al\r\ngorithms; Bigoh and Theta notations, Data Structures: \r\nArrays, Linked lists, Stacks (example\r\n: expression evaluation), Binary sear\r\nch trees, RedBlack trees, Hash \r\ntables, Sorting and Divide and Conquer Strategy: Merg\r\nesort; DandC with Matrix Multiplication as another \r\nexample, Quicksort with averag\r\ne case analysis, Heaps and heap\r\nsort, Lower bound on comparisonbased \r\nsorting and Counting sort, Radix so\r\nrt, Btrees, Dynamic Programming: \r\nmethodology and examples (Fibonacci \r\nnumbers, matrix sequence, multiplication, longest\r\n common subsequence, convex polygon triangulation), \r\nGreedy Method: Methodology, examples (lecture sche\r\nduling,process scheduling) \r\nand comparison with DP \r\n(more examples to come later in\r\n graph algorithms), Graph Algorithms: Basics of graphs and their \r\nrepresentations, BFS, DFS, Topologi\r\ncal sorting, Minimum spanning trees \r\n(Kruskal and Prims algorithms and \r\nbrief discussions of disjoint set a\r\nnd Fibonacci heap data structures), S\r\nhortest Paths (Dijks\r\ntra, BellmanFord, \r\nFloydWarshall). ', '', 'cs', 3, 0, 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
